<?php

namespace App\Filament\Pages;

use App\Models\User;
use App\Services\FullSystemBackupService;
use App\Services\FullSystemRestoreService;
use App\Services\StreamedDatabaseBackupService as DatabaseBackupService;
use BackedEnum;
use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Support\Icons\Heroicon;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Throwable;
use UnitEnum;

class DatabaseManagement extends Page
{
    use HasPageShield;

    protected string $view = 'filament.pages.database-management';

    protected static ?string $title = 'Database Management';

    protected static ?string $navigationLabel = 'Database Management';

    protected static string|BackedEnum|null $navigationIcon = Heroicon::ArrowDownTray;

    protected static string|UnitEnum|null $navigationGroup = 'Settings';

    protected static ?int $navigationSort = 4;

    protected function getHeaderActions(): array
    {
        return [
            ActionGroup::make([
                Action::make('downloadDatabaseBackup')
                    ->label('Database Backup')
                    ->icon(Heroicon::CircleStack)
                    ->modalHeading('Confirm Database Backup')
                    ->modalDescription('Download the database structure and records as a MySQL SQL file.')
                    ->modalSubmitActionLabel('Download SQL Backup')
                    ->schema([
                        $this->currentPasswordField(),
                    ])
                    ->action(fn (array $data): StreamedResponse => $this->downloadDatabaseBackup($data)),

                Action::make('downloadFullBackup')
                    ->label('Full System Backup')
                    ->icon(Heroicon::ArrowDownTray)
                    ->color('primary')
                    ->modalHeading('Create Encrypted Full System Backup')
                    ->modalDescription('Includes the database, profile photos, memos, leave files, and ticket attachments. Keep the backup password because it cannot be recovered.')
                    ->modalSubmitActionLabel('Download Full Backup')
                    ->schema([
                        $this->currentPasswordField(),
                        TextInput::make('backup_password')
                            ->label('Backup Password')
                            ->password()
                            ->revealable()
                            ->minLength(12)
                            ->autocomplete('new-password')
                            ->helperText('Use at least 12 characters. This password is required during restoration.')
                            ->required(),
                        TextInput::make('backup_password_confirmation')
                            ->label('Confirm Backup Password')
                            ->password()
                            ->revealable()
                            ->autocomplete('new-password')
                            ->required(),
                    ])
                    ->action(fn (array $data): BinaryFileResponse => $this->downloadFullBackup($data)),

                Action::make('restoreFullBackup')
                    ->label('Restore Full Backup')
                    ->icon(Heroicon::ArrowUpTray)
                    ->color('danger')
                    ->modalHeading('Restore Full System Backup')
                    ->modalDescription('This replaces the current database and managed uploads. A private safety backup is created first, and you will be signed out after a successful restore.')
                    ->modalSubmitActionLabel('Restore System')
                    ->schema([
                        $this->currentPasswordField(),
                        FileUpload::make('backup_archive')
                            ->label('Encrypted Full Backup')
                            ->disk('local')
                            ->directory('restore-uploads')
                            ->visibility('private')
                            ->acceptedFileTypes([
                                'application/zip',
                                'application/x-zip-compressed',
                                'application/octet-stream',
                            ])
                            ->maxSize(524288)
                            ->helperText('Upload a full-system ZIP generated by this page. Maximum application limit: 512 MB.')
                            ->required(),
                        TextInput::make('backup_password')
                            ->label('Backup Password')
                            ->password()
                            ->revealable()
                            ->minLength(12)
                            ->autocomplete('off')
                            ->required(),
                        TextInput::make('restore_confirmation')
                            ->label('Type RESTORE to continue')
                            ->helperText('Restoration cannot be undone from the browser after it starts.')
                            ->required(),
                    ])
                    ->visible(fn (): bool => auth()->user()?->hasRole('super_admin') ?? false)
                    ->action(fn (array $data): ?RedirectResponse => $this->restoreFullBackup($data)),
            ])
                ->label('Backup & Restore')
                ->icon(Heroicon::CircleStack)
                ->button(),
        ];
    }

    protected function currentPasswordField(): TextInput
    {
        return TextInput::make('current_password')
            ->label('Current Password')
            ->password()
            ->revealable()
            ->autocomplete('current-password')
            ->required();
    }

    protected function downloadDatabaseBackup(array $data): StreamedResponse
    {
        $this->authorizeCurrentUser($data);

        return app(DatabaseBackupService::class)->download();
    }

    protected function downloadFullBackup(array $data): BinaryFileResponse
    {
        $this->authorizeCurrentUser($data);
        $this->validateBackupPasswordConfirmation($data);

        return app(FullSystemBackupService::class)->download((string) $data['backup_password']);
    }

    protected function restoreFullBackup(array $data): ?RedirectResponse
    {
        $this->authorizeCurrentUser($data, superAdminOnly: true);

        if (($data['restore_confirmation'] ?? null) !== 'RESTORE') {
            throw ValidationException::withMessages([
                'restore_confirmation' => 'Type RESTORE exactly to confirm the full-system restoration.',
            ]);
        }

        $storedPath = $data['backup_archive'] ?? null;

        if (is_array($storedPath)) {
            $storedPath = reset($storedPath);
        }

        if (! is_string($storedPath) || $storedPath === '') {
            throw ValidationException::withMessages([
                'backup_archive' => 'Select a full-system backup ZIP file.',
            ]);
        }

        $disk = Storage::disk('local');

        if (! $disk->exists($storedPath)) {
            throw ValidationException::withMessages([
                'backup_archive' => 'The uploaded backup file could not be found.',
            ]);
        }

        try {
            app(FullSystemRestoreService::class)->restore(
                $disk->path($storedPath),
                (string) $data['backup_password'],
            );
        } catch (Throwable $exception) {
            report($exception);

            Notification::make()
                ->danger()
                ->title('System restore failed')
                ->body($exception->getMessage())
                ->persistent()
                ->send();

            return null;
        } finally {
            $disk->delete($storedPath);
        }

        auth()->logout();
        request()->session()->invalidate();
        request()->session()->regenerateToken();

        return redirect()
            ->to('/hr/login')
            ->with('status', 'The full-system backup was restored successfully. Sign in using an account contained in the restored backup.');
    }

    protected function authorizeCurrentUser(array $data, bool $superAdminOnly = false): User
    {
        $user = auth()->user();

        abort_unless($user instanceof User && in_array($user->role, ['admin', 'hr'], true), 403);

        if ($superAdminOnly) {
            abort_unless($user->hasRole('super_admin'), 403);
        }

        if (! Hash::check((string) ($data['current_password'] ?? ''), (string) $user->password)) {
            throw ValidationException::withMessages([
                'current_password' => 'The password is incorrect.',
            ]);
        }

        return $user;
    }

    protected function validateBackupPasswordConfirmation(array $data): void
    {
        if (($data['backup_password'] ?? null) !== ($data['backup_password_confirmation'] ?? null)) {
            throw ValidationException::withMessages([
                'backup_password_confirmation' => 'The backup passwords do not match.',
            ]);
        }
    }
}
